services:
  postgresql:
    container_name: go-ech-redis-postgresql
    image: postgres:latest
    env_file:
      - path: "../../.env"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DOCKER_DB_USER}
      POSTGRES_PASSWORD: ${DOCKER_DB_PASSWORD}
      POSTGRES_DB: ${DOCKER_DB_NAME}
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - echo-go-redis-infrastructure
  dragonfly:
    container_name: go-ech-redis-dragonfly
    image: "docker.dragonflydb.io/dragonflydb/dragonfly"
    command: --cluster_mode=emulated --lock_on_hashtags
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"
    volumes:
      - ./data/df:/data
    networks:
      - echo-go-redis-infrastructure
networks:
  echo-go-redis-infrastructure:
    driver: bridge
